### ISSUE TITLE
Alpinelinux errors

### ISSUE THREAD

**Issue by moiselazarus** [pandom79/Unitd#1]
Thank you for unitd, I like it. I could not boot my Alpine vm with it.
I compiled everthing without errors, than I linked /usr/unitd to /sbin/init and rebooted.
Here is a screenshoot
![Screenshot_2022-06-29_07-53-29](https://user-images.githubusercontent.com/5489418/176523007-77862778-da67-45c4-9199-43ec9db3797d.png)

**Comment by pandom79** [comment]
Thanks for your feedback.
From your screenshot, the errors seem two.
1) **seedrng** command is missing. You could fix downloading it from [void linux runit](https://github.com/void-linux/void-runit), build and put it in /usr/sbin.
2) Check **/usr/share/unitd/init.state/scripts/unitd-check.sh** is here.

Please note, when unitd boots the first time, it needs at least of a **agetty** or similar unit for load the terminal and add a symlink this unit in the **multi-user-net state** which is the default. 
For example:
`ln -s /usr/lib64/unitd/units/agetty-1.unit /etc/unitd/units/multi-user-net.state/.`
An example of agetty or similar is [here](https://github.com/pandom79/Unitd/blob/master/src/extra/units/agetty-1.unit).
In this unit, you should check the run property path as well.

Anyway, I'll add seedrng program to unitd sources and much probably I'll have to add PATH environment variable for all init and final scripts because unfortunately, every distro chooses their paths.
Let me know if it's working.

**Comment by moiselazarus** [comment]
Thanks for the quick response.
One error is gone, but unitd-check is still there. The file exist.
![Screenshot_2022-06-30_13-01-30](https://user-images.githubusercontent.com/5489418/176662320-c05b3d75-fdcb-47f5-b97d-e88f40beded7.png)
Where is the default place for my own units, for example the agetty. I don't have /usr/lib64.
I createted /etc/unitd/units/multi-user-net.state/ and then
ln -s /home/user/unitd/Unitd/src/extra/units/agetty-1.unit /etc/unitd/units/multi-user-net.state/

**Comment by pandom79** [comment]
Please, you wait for some days. I'm changing documentation and code.

**Comment by pandom79** [comment]
Download the beta release and follow the [guide](https://github.com/pandom79/Unitd#build-instructions).

**Comment by moiselazarus** [comment]
Thanks, now it doesn't compile, it complaints about unitd-check.
![Screenshot_2022-07-01_21-04-12](https://user-images.githubusercontent.com/5489418/176955885-d4ce1526-7ad2-4d14-bd65-edd8ca410f1b.png)
Alpine doesn't have a /usr/lib64, maybe you implement, if I compile with -DOS_NAME="Alpinelinux" it will default to /usr/lib.

**Comment by pandom79** [comment]
Please, can you post the unitd_config.h content? It's into build folder.

**Comment by moiselazarus** [comment]
#define OS_NAME "Linux"
#define OUR_UTMP_FILE "/var/run/utmp"
#define OUR_WTMP_FILE "/var/log/wtmp"
#define UNITS_PATH "/usr/lib/unitd/units"
#define UNITS_ENAB_PATH "/etc/unitd/units"
#define UNITD_DATA_PATH "/usr/share/unitd"
#define UNITD_LOG_PATH "/var/log/unitd.log"
#define UNITD_CONF_PATH "/etc/unitd"
#undef UNITD_TEST

**Comment by pandom79** [comment]
As you can see, the paths are correct. This is not a unitd bug.

**Comment by moiselazarus** [comment]
How can I debug? before it compiled. What is this line 34 syntax error: bad substitution.
Is the lib64 somewhere hardcoded?

**Comment by pandom79** [comment]
You can run "sh unitd-check.sh" replacing UNITS_PATH and UNITS_ENAB_PATH with the values of unitd_config.h. moreover, check if /bin/sh not pointing to something else.
Maybe on Alpine this script is interpreted in other way.

**Comment by moiselazarus** [comment]
/bin/sh -> /bin/busybox

**Comment by pandom79** [comment]
I strongly think this is the problem. You can resolve it. Tomorrow I explain how to do. It's very simple.

**Comment by moiselazarus** [comment]
Thank you! good evening, salute, grazie mille

**Comment by pandom79** [comment]
Could you link /bin/sh to /bin/bash and retry?
Unitd uses Sh posix shell

**Comment by moiselazarus** [comment]
Perfect, it compiled. I linked and restarted. Now I have a little problem with my agetty.unit
![Screenshot_2022-07-01_22-20-45](https://user-images.githubusercontent.com/5489418/176963646-3705d823-75dd-4b6b-97b2-540ab097019a.png)
t

**Comment by pandom79** [comment]
Alpine uses Openrc as init. You could see how they are configured and set that command in agetty unit.

**Comment by moiselazarus** [comment]
I keep you updated. I have to rebuild the VM, because I have no emergency shell.

**Comment by pandom79** [comment]
Ok. When we will make enough test and Unitd will be stable then I'll implement the user unit management as well to allow monitoring the user processes like pipewire, wireplumber and so on.

**Comment by moiselazarus** [comment]
Perfect, Openrc is to slow. I'll use unitd. And try do make a template for Qubes. Here we need a fast starting VM.

**Comment by pandom79** [comment]
Ok. I close it.
For whatever problem just open a new issue.
Regards
